name: build qrcode

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

  workflow_dispatch: {}

jobs:
  # build
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install build requirement 
        run: |
          sudo apt update
          sudo apt install -y python3 python3-venv python3-pip p7zip-full

      - name: build product list and qrcode
        run: make all

      # upload build file 
      - name: Upload product list
        uses: actions/upload-artifact@v4
        with:
          name: build-prod-list
          path: .build/product-list.json

      - name: Upload qrcode
        uses: actions/upload-artifact@v4
        with:
          name: build-release-qrcode
          path: .build/qrcode.7z

  # release file 
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: get build prod list
        uses: actions/download-artifact@v4
        with:
          name: build-prod-list
          path: .build/

      - name: get build qrcode
        uses: actions/download-artifact@v4
        with:
          name: build-release-qrcode
          path: .build/

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: release ${{ github.ref_name }}
          prerelease: ${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}

          body: |
            release qr code file

          files: |
            ./build/product-list.json
            ./build/qrcode.7z:release-qrcode-${{ github.ref_name }}.7z 

